export const allHomes = [
  {
    id: 1,
    slug: "imovel-1",
    price: "R$ 2.300.000,00",
    size: 300,
    garage: 4,
    bedrooms: 5,
    bathrooms: 1,
    images: [
      "/homes/imovel-1/imovel-1.jpeg",
      "/homes/imovel-1/imovel-2.jpeg",
      "/homes/imovel-1/imovel-3.jpeg",
      "/homes/imovel-1/imovel-4.jpeg",
      "/homes/imovel-1/imovel-5.jpeg",
      "/homes/imovel-1/imovel-6.jpeg",
      "/homes/imovel-1/imovel-7.jpeg",
      "/homes/imovel-1/imovel-8.jpeg",
      "/homes/imovel-1/imovel-9.jpeg",
      "/homes/imovel-1/imovel-10.jpeg",
      "/homes/imovel-1/imovel-11.jpeg",
      "/homes/imovel-1/imovel-12.jpeg",
      "/homes/imovel-1/imovel-13.jpeg",
      "/homes/imovel-1/imovel-14.jpeg",
      "/homes/imovel-1/imovel-15.jpeg",
      "/homes/imovel-1/imovel-16.jpeg",
      "/homes/imovel-1/imovel-17.jpeg",
      "/homes/imovel-1/imovel-18.jpeg",
      "/homes/imovel-1/imovel-19.jpeg",
      "/homes/imovel-1/imovel-20.jpeg",
      "/homes/imovel-1/imovel-21.jpeg",
      "/homes/imovel-1/imovel-22.jpeg",
      "/homes/imovel-1/imovel-23.jpeg",
      "/homes/imovel-1/imovel-24.jpeg",
      "/homes/imovel-1/imovel-25.jpeg",
      "/homes/imovel-1/imovel-26.jpeg",
      "/homes/imovel-1/imovel-27.jpeg",
    ],
    address: "Mogi das cruzes",
    description: "Condomínio Veredas",
    homeDescription:
      "Apartamento com 5 quartos e 1 banheiro à venda, 300 m² por R$ 2.300.000,00\n\nLocalizado em Mogi das Cruzes, o Condomínio Veredas oferece conforto e segurança para toda a família. O imóvel conta com 5 dormitórios, ideal para famílias grandes ou quem busca espaço extra. Além disso, possui 4 vagas de garagem, proporcionando comodidade e segurança para seus veículos.\n\nA localização é privilegiada, próxima a escolas, restaurantes, farmácias e comércios em geral. O empreendimento é uma excelente opção para quem procura qualidade de vida e lazer sem sair de casa.\n\nAgende já sua visita!",
  },
  {
    id: 2,
    slug: "imovel-2",
    price: "R$ 230.000,00",
    size: 50,
    bedrooms: 2,
    bathrooms: 1,
    garage: 1,
    images: [
      "/homes/imovel-2/imovel-1.jpeg",
      "/homes/imovel-2/imovel-2.jpeg",
      "/homes/imovel-2/imovel-3.jpeg",
      "/homes/imovel-2/imovel-4.jpeg",
      "/homes/imovel-2/imovel-5.jpeg",
      "/homes/imovel-2/imovel-6.jpeg",
      "/homes/imovel-2/imovel-7.jpeg",
      "/homes/imovel-2/imovel-8.jpeg",
      "/homes/imovel-2/imovel-9.jpeg",
      "/homes/imovel-2/imovel-10.jpeg",
      "/homes/imovel-2/imovel-11.jpeg",
      "/homes/imovel-2/imovel-12.jpeg",
      "/homes/imovel-2/imovel-13.jpeg",
      "/homes/imovel-2/imovel-14.jpeg",
      "/homes/imovel-2/imovel-15.jpeg",
      "/homes/imovel-2/imovel-16.jpeg",
      "/homes/imovel-2/imovel-17.jpeg",
      "/homes/imovel-2/imovel-18.jpeg",
      "/homes/imovel-2/imovel-19.jpeg",
      "/homes/imovel-2/imovel-20.jpeg",
      "/homes/imovel-2/imovel-21.jpeg",
      "/homes/imovel-2/imovel-22.jpeg",
      "/homes/imovel-2/imovel-23.jpeg",
      "/homes/imovel-2/imovel-24.jpeg",
      "/homes/imovel-2/imovel-25.jpeg",
    ],
    address: "Suzano Casa Branca SP",
    description: "Condomínio Predilleto",
    homeDescription:
      "Este apartamento compacto de 2 quartos e 1 banheiro, com 50 m², está disponível por R$ 230.000,00. O imóvel é ideal para casais ou indivíduos que buscam praticidade e conforto em um bairro tranquilo. O condomínio oferece segurança e áreas comuns bem cuidadas, proporcionando uma ótima qualidade de vida. Possui uma vaga de garagem e localização conveniente, com fácil acesso ao transporte público, escolas e comércios.",
  },
  {
    id: 3,
    slug: "imovel-3",
    price: "R$ 185.000,00",
    size: "-",
    garage: 1,
    bedrooms: 2,
    bathrooms: 1,
    images: [
      "/homes/imovel-3/imovel-1.jpeg",
      "/homes/imovel-3/imovel-2.jpeg",
      "/homes/imovel-3/imovel-3.jpeg",
      "/homes/imovel-3/imovel-4.jpeg",
      "/homes/imovel-3/imovel-5.jpeg",
      "/homes/imovel-3/imovel-6.jpeg",
      "/homes/imovel-3/imovel-7.jpeg",
      "/homes/imovel-3/imovel-8.jpeg",
      "/homes/imovel-3/imovel-9.jpeg",
      "/homes/imovel-3/imovel-10.jpeg",
      "/homes/imovel-3/imovel-11.jpeg",
      "/homes/imovel-3/imovel-12.jpeg",
      "/homes/imovel-3/imovel-13.jpeg",
      "/homes/imovel-3/imovel-14.jpeg",
      "/homes/imovel-3/imovel-15.jpeg",
      "/homes/imovel-3/imovel-16.jpeg",
      "/homes/imovel-3/imovel-17.jpeg",
    ],
    address:
      "Braz Cubas, Mogi das Cruzes - SP",
    description: "Condomínio Manacá",
    homeDescription:
      "Com 2 quartos e 1 banheiro, este imóvel no Condomínio Manacá está disponível por R$ 185.000,00. O condomínio oferece infraestrutura de segurança e lazer, com acesso fácil às principais vias da cidade. Ideal para quem busca praticidade e um bom custo-benefício, o imóvel também conta com 1 vaga de garagem. O bairro é tranquilo e oferece fácil acesso a escolas e pontos comerciais.",
  },
  {
    id: 4,
    slug: "imovel-4",
    price: "R$ 350.000,00",
    size: "-",
    bedrooms: 3,
    bathrooms: 2,
    garage: 0,
    images: [
      "/homes/imovel-4/imovel-1.jpeg",
      "/homes/imovel-4/imovel-2.jpeg",
      "/homes/imovel-4/imovel-3.jpeg",
      "/homes/imovel-4/imovel-4.jpeg",
      "/homes/imovel-4/imovel-5.jpeg",
      "/homes/imovel-4/imovel-6.jpeg",
      "/homes/imovel-4/imovel-7.jpeg",
      "/homes/imovel-4/imovel-8.jpeg",
      "/homes/imovel-4/imovel-9.jpeg",
      "/homes/imovel-4/imovel-10.jpeg",
      "/homes/imovel-4/imovel-11.jpeg",
      "/homes/imovel-4/imovel-12.jpeg",
      "/homes/imovel-4/imovel-13.jpeg",
      "/homes/imovel-4/imovel-14.jpeg",
      "/homes/imovel-4/imovel-15.jpeg",
      "/homes/imovel-4/imovel-16.jpeg",
      "/homes/imovel-4/imovel-17.jpeg",
      "/homes/imovel-4/imovel-18.jpeg",
      "/homes/imovel-4/imovel-19.jpeg",
      "/homes/imovel-4/imovel-20.jpeg",
      "/homes/imovel-4/imovel-21.jpeg",
    ],
    address: "Poá",
    description: "Condomínio Bonini",
    homeDescription:
      "Este imóvel de 3 quartos e 2 banheiros, localizado no Condomínio Bonini, está à venda por R$ 350.000,00. Ideal para quem busca um espaço confortável, este imóvel é perfeito para famílias. Embora não tenha garagem, a localização oferece fácil acesso ao transporte público e áreas comerciais, proporcionando praticidade no dia a dia. O condomínio conta com segurança 24h e áreas de lazer para toda a família.",
  },
  {
    id: 5,
    slug: "imovel-5",
    price: "R$ 200.000,00",
    size: "-",
    bedrooms: 2,
    bathrooms: 1,
    garage: 0,
    images: [
      "/homes/imovel-5/imovel-1.jpeg",
      "/homes/imovel-5/imovel-2.jpeg",
      "/homes/imovel-5/imovel-3.jpeg",
      "/homes/imovel-5/imovel-4.jpeg",
      "/homes/imovel-5/imovel-5.jpeg",
      "/homes/imovel-5/imovel-6.jpeg",
      "/homes/imovel-5/imovel-7.jpeg",
      "/homes/imovel-5/imovel-8.jpeg",
      "/homes/imovel-5/imovel-9.jpeg",
      "/homes/imovel-5/imovel-10.jpeg",
      "/homes/imovel-5/imovel-11.jpeg",
      "/homes/imovel-5/imovel-12.jpeg",
      "/homes/imovel-5/imovel-13.jpeg",
      "/homes/imovel-5/imovel-14.jpeg",
      "/homes/imovel-5/imovel-15.jpeg",
      "/homes/imovel-5/imovel-16.jpeg",
    ],
    address:
      "Jardim Santa Teresa, Mogi das Cruzes",
    description: "Brás Cubas Santa Tereza",
    homeDescription:
      "Este aconchegante imóvel de 2 quartos e 1 banheiro, localizado no bairro Jardim Santa Teresa, em Mogi das Cruzes, está disponível por R$ 200.000,00. Ideal para quem busca um lar simples e funcional, o imóvel oferece boa ventilação e iluminação natural. A localização é excelente, próxima a escolas, supermercados e pontos de transporte, oferecendo toda a comodidade necessária para o dia a dia.",
  },
  {
    id: 6,
    slug: "imovel-6",
    price: "R$ 780.000,00",
    size: 85,
    bedrooms: 3,
    bathrooms: 2,
    garage: 2,
    images: [
      "/homes/imovel-6/imovel-1.jpeg",
      "/homes/imovel-6/imovel-2.jpeg",
      "/homes/imovel-6/imovel-3.jpeg",
      "/homes/imovel-6/imovel-4.jpeg",
      "/homes/imovel-6/imovel-5.jpeg",
      "/homes/imovel-6/imovel-6.jpeg",
      "/homes/imovel-6/imovel-7.jpeg",
      "/homes/imovel-6/imovel-8.jpeg",
      "/homes/imovel-6/imovel-9.jpeg",
      "/homes/imovel-6/imovel-10.jpeg",
      "/homes/imovel-6/imovel-11.jpeg",
      "/homes/imovel-6/imovel-12.jpeg",
      "/homes/imovel-6/imovel-13.jpeg",
      "/homes/imovel-6/imovel-14.jpeg",
      "/homes/imovel-6/imovel-15.jpeg",
      "/homes/imovel-6/imovel-16.jpeg",
      "/homes/imovel-6/imovel-17.jpeg",
    ],
    address:
      "Vila Mogilar, Mogi das Cruzes - SP",
    description: "Condomínio Green Valle.",
    homeDescription:
      "Este apartamento de 3 quartos e 2 banheiros, com 85 m², está à venda por R$ 780.000,00 no Condomínio Green Valle. O imóvel oferece um ótimo espaço interno, perfeito para famílias, com 2 vagas de garagem e áreas de lazer no condomínio. A localização é excelente, com acesso fácil a escolas, comércios e principais vias da cidade. Além disso, a segurança e o conforto do condomínio tornam este imóvel uma excelente opção para quem busca qualidade de vida.",
  },
  {
    id: 7,
    slug: "imovel-7",
    price: "R$ 260.000,00",
    size: 75,
    bedrooms: 2,
    bathrooms: 2,
    garage: 1,
    images: [
      "/homes/imovel-7/imovel-1.jpeg",
      "/homes/imovel-7/imovel-2.jpeg",
      "/homes/imovel-7/imovel-3.jpeg",
      "/homes/imovel-7/imovel-4.jpeg",
      "/homes/imovel-7/imovel-5.jpeg",
      "/homes/imovel-7/imovel-6.jpeg",
      "/homes/imovel-7/imovel-7.jpeg",
      "/homes/imovel-7/imovel-8.jpeg",
      "/homes/imovel-7/imovel-9.jpeg",
      "/homes/imovel-7/imovel-10.jpeg",
      "/homes/imovel-7/imovel-11.jpeg",
      "/homes/imovel-7/imovel-12.jpeg",
      "/homes/imovel-7/imovel-13.jpeg",
      "/homes/imovel-7/imovel-14.jpeg",
      "/homes/imovel-7/imovel-15.jpeg",
      "/homes/imovel-7/imovel-16.jpeg",
      "/homes/imovel-7/imovel-17.jpeg",
      "/homes/imovel-7/imovel-18.jpeg",
      "/homes/imovel-7/imovel-19.jpeg",
      "/homes/imovel-7/imovel-20.jpeg",
      "/homes/imovel-7/imovel-21.jpeg",
      "/homes/imovel-7/imovel-22.jpeg",
      "/homes/imovel-7/imovel-23.jpeg",
      "/homes/imovel-7/imovel-24.jpeg",
      "/homes/imovel-7/imovel-25.jpeg",
      "/homes/imovel-7/imovel-26.jpeg",
      "/homes/imovel-7/imovel-27.jpeg",
      "/homes/imovel-7/imovel-28.jpeg",
      "/homes/imovel-7/imovel-29.jpeg",
      "/homes/imovel-7/imovel-30.jpeg",
    ],
    address: "Mogi das cruzes",
    description: "Sobrado em condomínio.",
    homeDescription:
      "Este imóvel no Condomínio Novo Horizonte, com 3 quartos e 2 banheiros, está à venda por R$ 260.000,00. O imóvel é ideal para famílias que buscam conforto e praticidade, com 1 vaga de garagem. O condomínio oferece infraestrutura de segurança, além de fácil acesso a escolas, transporte público e pontos comerciais. Se você procura um lar bem localizado e com excelente custo-benefício, esta é a opção ideal.",
  },
  {
    id: 8,
    slug: "imovel-8",
    price: "R$ 750.000,00",
    size: 70,
    bedrooms: 2,
    bathrooms: 2,
    garage: 1,
    images: [
      "/homes/imovel-8/imovel-1.jpeg",
      "/homes/imovel-8/imovel-2.jpeg",
      "/homes/imovel-8/imovel-3.jpeg",
      "/homes/imovel-8/imovel-4.jpeg",
      "/homes/imovel-8/imovel-5.jpeg",
      "/homes/imovel-8/imovel-6.jpeg",
      "/homes/imovel-8/imovel-7.jpeg",
      "/homes/imovel-8/imovel-8.jpeg",
      "/homes/imovel-8/imovel-9.jpeg",
      "/homes/imovel-8/imovel-10.jpeg",
      "/homes/imovel-8/imovel-11.jpeg",
      "/homes/imovel-8/imovel-12.jpeg",
      "/homes/imovel-8/imovel-13.jpeg",
      "/homes/imovel-8/imovel-14.jpeg",
      "/homes/imovel-8/imovel-15.jpeg",
      "/homes/imovel-8/imovel-16.jpeg",
    ],
    address: "Mogi das Cruzes",
    description: "Condomínio My Helbor.",
    homeDescription:
      "Condomínio My Helbor em Mogi das Cruzes. Um imóvel de 70 m², com 2 dormitórios, 2 banheiros e 1 vaga de garagem. Perfeito para quem busca conforto e segurança em uma localização privilegiada.",
  },
  {
    id: 9,
    slug: "imovel-9",
    price: "R$ 220.000,00",
    size: 54,
    bedrooms: 2,
    bathrooms: 1,
    garage: 1,
    images: [
      "/homes/imovel-9/imovel-1.jpeg",
      "/homes/imovel-9/imovel-2.jpeg",
      "/homes/imovel-9/imovel-3.jpeg",
      "/homes/imovel-9/imovel-4.jpeg",
      "/homes/imovel-9/imovel-5.jpeg",
      "/homes/imovel-9/imovel-6.jpeg",
      "/homes/imovel-9/imovel-7.jpeg",
      "/homes/imovel-9/imovel-8.jpeg",
      "/homes/imovel-9/imovel-9.jpeg",
      "/homes/imovel-9/imovel-10.jpeg",
      "/homes/imovel-9/imovel-11.jpeg",
      "/homes/imovel-9/imovel-12.jpeg",
      "/homes/imovel-9/imovel-13.jpeg",
      "/homes/imovel-9/imovel-14.jpeg",
      "/homes/imovel-9/imovel-15.jpeg",
      "/homes/imovel-9/imovel-16.jpeg",
      "/homes/imovel-9/imovel-17.jpeg",
      "/homes/imovel-9/imovel-18.jpeg",
    ],
    address: "Vila Urupês Suzano",
    description: "Condomínio Portal das Artes.",
    homeDescription:
      "Condomínio Portal das Artes em Vila Urupês, Suzano. Imóvel de 54 m² com 2 quartos, 1 banheiro e 1 vaga de garagem. Ideal para quem deseja morar em um lugar tranquilo e com excelente infraestrutura.",
  },
  {
    id: 10,
    slug: "imovel-10",
    price: "R$ 212.000,00",
    size: 54,
    bedrooms: 2,
    bathrooms: 1,
    garage: 1,
    images: [
      "/homes/imovel-10/imovel-1.jpeg",
      "/homes/imovel-10/imovel-2.jpeg",
      "/homes/imovel-10/imovel-3.jpeg",
      "/homes/imovel-10/imovel-4.jpeg",
      "/homes/imovel-10/imovel-5.jpeg",
      "/homes/imovel-10/imovel-6.jpeg",
      "/homes/imovel-10/imovel-7.jpeg",
      "/homes/imovel-10/imovel-8.jpeg",
      "/homes/imovel-10/imovel-9.jpeg",
      "/homes/imovel-10/imovel-10.jpeg",
      "/homes/imovel-10/imovel-11.jpeg",
    ],
    address: "Vila Urupês Suzano",
    description: "Condomínio Portal das Artes",
    homeDescription:
      "Condomínio Portal das Artes em Vila Urupês, Suzano. Apartamento de 54 m², com 2 quartos, 1 banheiro e 1 vaga de garagem. Uma excelente opção para quem busca qualidade de vida e praticidade.",
  },
  {
    id: 11,
    slug: "imovel-11",
    price: "R$ 222.000,00",
    size: 155,
    bedrooms: 0,
    bathrooms: 0,
    garage: 0,
    images: [
      "/homes/imovel-11/imovel-1.jpeg",
      "/homes/imovel-11/imovel-2.jpeg",
      "/homes/imovel-11/imovel-3.jpeg",
      "/homes/imovel-11/imovel-4.jpeg",
    ],
    address: "Jardim Lincoln Suzano",
    description: "Terreno plano 5x31.",
    homeDescription:
      "Terreno plano de 155 m² no Jardim Lincoln, Suzano. Com medidas de 5x31, esse terreno oferece amplo espaço para construção, ideal para quem busca investir ou construir seu lar.",
  },
  {
    id: 12,
    slug: "imovel-12",
    price: "R$ 480.000,00",
    size: "74,84",
    bedrooms: 2,
    bathrooms: 3,
    garage: 2,
    images: [
      "/homes/imovel-12/imovel-1.jpeg",
      "/homes/imovel-12/imovel-2.jpeg",
      "/homes/imovel-12/imovel-3.jpeg",
      "/homes/imovel-12/imovel-4.jpeg",
      "/homes/imovel-12/imovel-5.jpeg",
      "/homes/imovel-12/imovel-6.jpeg",
      "/homes/imovel-12/imovel-7.jpeg",
      "/homes/imovel-12/imovel-8.jpeg",
      "/homes/imovel-12/imovel-9.jpeg",
      "/homes/imovel-12/imovel-10.jpeg",
      "/homes/imovel-12/imovel-11.jpeg",
      "/homes/imovel-12/imovel-12.jpeg",
    ],
    address: "Vila Urupês Suzano",
    description: "Condomínio Portal das Artes .",
    homeDescription:
      "Condomínio Portal das Artes em Vila Urupês, Suzano. Apartamento de 74,84 m², com 2 quartos, 3 banheiros e 2 vagas de garagem. Um espaço moderno e aconchegante para você e sua família viverem com qualidade.",
  },
  {
    id: 13,
    slug: "imovel-13",
    price: "R$ 750.000,00",
    size: "3000",
    bedrooms: "",
    bathrooms: "",
    garage: "",
    images: [
      "/homes/imovel-13/imovel-1.jpeg",
      "/homes/imovel-13/imovel-2.jpeg",
      "/homes/imovel-13/imovel-3.jpeg",
      "/homes/imovel-13/imovel-4.jpeg",
      "/homes/imovel-13/imovel-5.jpeg",
      "/homes/imovel-13/imovel-6.jpeg",
      "/homes/imovel-13/imovel-7.jpeg",
      "/homes/imovel-13/imovel-8.jpeg",
      "/homes/imovel-13/imovel-9.jpeg",
      "/homes/imovel-13/imovel-10.jpeg",
      "/homes/imovel-13/imovel-11.jpeg",
      "/homes/imovel-13/imovel-12.jpeg",
      "/homes/imovel-13/imovel-13.jpeg",
      "/homes/imovel-13/imovel-14.jpeg",
      "/homes/imovel-13/imovel-15.jpeg",
      "/homes/imovel-13/imovel-16.jpeg",
      "/homes/imovel-13/imovel-17.jpeg",
      "/homes/imovel-13/imovel-18.jpeg",
      "/homes/imovel-13/imovel-19.jpeg",
      "/homes/imovel-13/imovel-20.jpeg",
      "/homes/imovel-13/imovel-21.jpeg",
      "/homes/imovel-13/imovel-22.jpeg",
      "/homes/imovel-13/imovel-23.jpeg",
      "/homes/imovel-13/imovel-24.jpeg",
      "/homes/imovel-13/imovel-25.jpeg",
      "/homes/imovel-13/imovel-26.jpeg",
      "/homes/imovel-13/imovel-27.jpeg",
      "/homes/imovel-13/imovel-28.jpeg",
      "/homes/imovel-13/imovel-29.jpeg",
      "/homes/imovel-13/imovel-30.jpeg",
      "/homes/imovel-13/imovel-31.jpeg",
      "/homes/imovel-13/imovel-32.jpeg",
      "/homes/imovel-13/imovel-33.jpeg",
      "/homes/imovel-13/imovel-34.jpeg",
    ],
    address: "Chácara dos Fernandes - Estância Paulista",
    description: "Chácara com diversas casas, lazer e muito mais!",
    homeDescription: `
    Chácara dos Fernandes - Estância Paulista

    Localizada na Rua Virgílio Gonçalves Capela, Estância Paulista, esta propriedade oferece uma área total de 3.000 m², com 500 m² de área construída. Avaliada em R$820.000,00, está sendo anunciada por R$750.000,00, apresentando uma excelente oportunidade de investimento.

    A chácara é composta por diversas edificações e estruturas de lazer:

    - **Casa Matriz**: Contendo 4 quartos, 3 banheiros, 2 cozinhas, uma ampla sala de estar, lavanderia e varanda.
    - **Casa do Lago**: Com 4 quartos, 2 banheiros, cozinha, sala e área com churrasqueira.
    - **Chalé**: Equipado com sala, cozinha, banheiro, quarto e lavanderia.
    - **Casa de Caseiro**: Possui sala, cozinha, banheiro, lavanderia e quarto, ideal para apoio na administração do imóvel.

    Entre as atrações de lazer, a propriedade conta com:
    - Piscina adulto e infantil
    - Quiosque com churrasqueira
    - Campo de futebol
    - Sala de jogos
    - Lago ornamental
    - Parquinho infantil
    - Bosque com árvores frutíferas
    - Área com forno e churrasqueira

    Além disso, a chácara oferece amplo estacionamento e está totalmente murada, com 54 metros de frente para a rua.

    Esta é uma excelente oportunidade para quem busca um refúgio tranquilo e bem estruturado, com diversas opções de lazer e conforto, em um ambiente totalmente privativo.
  `,
  },
  {
    id: 14,
    slug: "imovel-14",
    price: "R$ 1.800.000,00",
    size: "5565",
    bedrooms: "",
    bathrooms: "",
    garage: "",
    images: [
      "/homes/imovel-14/imovel-1.jpeg",
      "/homes/imovel-14/imovel-2.jpeg",
      "/homes/imovel-14/imovel-3.jpeg",
      "/homes/imovel-14/imovel-4.jpeg",
      "/homes/imovel-14/imovel-5.jpeg",
    ],
    address: "Altos de Suzano/Cidade Edson",
    description: "Uma das melhores da região!",
    homeDescription: `
    Rua das Chácaras - Altos de Suzano / Cidade Edson
    
    Localizada na Rua das Chácaras, no Altos de Suzano, Cidade Edson, esta propriedade possui uma área total de 5.565 m², com 1.100 m² de área construída. Está à venda por R$1.800.000,00 e é uma excelente oportunidade para diversos tipos de investidores.
  
    A propriedade é totalmente murada, com 80 metros de frente, e possui diversas edificações:
  
    - 1 Casa de 140 m², composta por 6 quartos, 2 salas, 3 banheiros e 2 cozinhas.
    - Salão de Festas com 6 banheiros e cozinha industrial, ideal para grandes eventos.
    - Sala de Jogos com 2 banheiros e cozinha americana.
    - Área de Churrasqueira/Forno e infraestrutura anexa, pronta para uso.
    
    A propriedade também oferece um amplo espaço coberto, que pode ser utilizado para conferências, reuniões, locações para empresas, escolas, igrejas e eventos em geral, com capacidade para até 500 pessoas.
  
    Além disso, há outras áreas preparadas para construção de novas edificações.
  
    O imóvel oferece um amplo estacionamento com capacidade para até 80 vagas.
  
    Observação: Nosso entendimento é que a venda deste imóvel pode ser ampliada para clientes que:
    
    1. Queiram morar em uma chácara.
    2. Igrejas, empresas e escolas que desejam ter espaço próprio para entretenimento.
    3. Organizadores de eventos.
    4. Concorrentes.
    5. Empreendedores que queiram construir mais casas no local para locação ou condomínio.
    `,
  },
];
